### ISSUE TITLE
About the dataset

### ISSUE THREAD

**Issue by tyxiong23** [Dongping-Chen/MLLM-Judge#5]
Hi authors, in the paper you mentioned that you included image-question pairs from CC3M. But I didn't find them in Dataset/Benchmark/score.jsonl. Instead, I found data from llava_bench. Are they the same?

**Comment by Dongping-Chen** [comment]
Yes, they are the same. We first chose llava_bench (-wild), but its size does not meet our expectations. Therefore, we use CC3M.
